version: '3.10'

services:
  postgres:
    image: postgres:15
    container_name: spdl-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: ./backend
    container_name: spdl-backend
    command: ["bash", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "mydatabase"
    ports:
      - "4000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    image: spdl-frontend
    environment:
      REACT_APP_API_URL: "http://fastapi:8000" # Use the Docker service name

volumes:
  postgres_data:
