services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"