version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spdl-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: spdl-backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "mydatabase"
    ports:
      - "4000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:

