// src/constants/constants.js

export const BILL_DESCRIPTIONS = [
    { value: "Signing Money", label: "সাইনিং মানি (Signing Money)" },
    { value: "Project Deposit", label: " জমা (Project Deposit)" },
    { value: "Deed", label: "দলিল (Deed)" },
    { value: "Architect", label: "আর্কিটেক্ট (Architect)" },
    { value: "Plan Pass/Approval", label: "প্ল্যান পাশ/অনুমোদন (Plan Pass/Approval)" },
    { value: "Miscellaneous", label: "বিবিধ (Miscellaneous)" },
    { value: "Sign Board", label: "সাইন বোর্ড (Sign Board)" },
    { value: "Utility", label: "ইউটিলিটি (Utility)" },
    { value: "Guard Salary", label: "গার্ডের বেতন (Guard Salary)" },
    { value: "Sanitary Expense", label: "পানিসম্পদ খরচ (Sanitary Expense)" },
    { value: "Piling Expense", label: "পাইলিং খরচ (Piling Expense)" },
    { value: "Steel Rod Purchase", label: "রড কেনা (Steel Rod Purchase)" },
    { value: "Cement", label: "সিমেন্ট (Cement)" },
    { value: "Sand", label: "বালি (Sand)" },
    { value: "Stone", label: "পাথর (Stone)" },
    { value: "Electrician", label: "ইলেকট্রিশিয়ান (Electrician)" },
    { value: "Electric Items Purchase", label: "বৈদ্যুতিক সরঞ্জাম কেনা (Electric Items Purchase)" },
    { value: "Mati Kata", label: "মাটি কাটা (Mati Kata)" },
    { value: "Raj Mistri Head", label: "রাজ মিস্ত্রি হেড (Raj Mistri Head)" },
    { value: "Raj Mistri Helper", label: "রাজ মিস্ত্রি সহকারী (Raj Mistri Helper)" },
    { value: "Rod Mistri Head", label: "রড মিস্ত্রি হেড(Rod Mistri Head)" },
    { value: "Rod Mistri Helper", label: "রড মিস্ত্রি সহকারী (Rod Mistri Helper)" },
    { value: "Am Kat", label: "আম গাছ কাটা (Am Kat)" },
    { value: "Concrete-Casting", label: "ঢালাই (Concrete Casting)" },
    { value: "Purchased Bamboo", label: "বাঁশ কেনা (Purchased Bamboo)" },
    { value: "Hardware Materials", label: "হার্ডওয়্যার মালামাল (Hardware Materials)" },
    { value: "Bricks Purchase", label: "ইট ক্রয় (Bricks Purchase)" },
    { value: "Tiles Purchase", label: "টাইলস ক্রয় (Tiles Purchase)" },
    { value: "Tiles Assembler Head", label: "টাইলস মিস্ত্রি হেড(Tiles Assembler Head)" },
    { value: "Tiles Assembler Helper", label: "টাইলস মিস্ত্রি সহকারী (Tiles Assembler Helper)" },
    { value: "Chipping Head", label: "চিপিং মিস্ত্রি হেড (Chipping Head)" },
    { value: "Chipping Helper", label: "চিপিং মিস্ত্রি সহকারী (Chipping Helper)" },
    { value: "Paint Purchase", label: "রং ক্রয় (Paint Purchase)" },
    { value: "Day Labour Bill", label: "দিনমজুর বিল (Day Labour Bill)" },
    { value: "Door Frame Purchase", label: "চৌকাঠ ক্রয় (Door Frame Purchase)" },
    { value: "Door Purchase", label: "দরজা ক্রয় (Door Purchase)" },
    { value: "Thai Glass Purchase", label: "থাই গ্লাস ক্রয় (Thai Glass Purchase)" },
    { value: "Engineer Salary", label: "ইঞ্জিনিয়ার বেতন (Engineer Salary)" },
    { value: "Maid Salary", label: "বুয়া বেতন (Maid Salary)" },
    { value: "Head Painter", label: "রং মিস্ত্রি হেড (Head Painter)" },
    { value: "Painter's Helper", label: "রং মিস্ত্রি সহকারী (Painter's Helper)" },
    { value: "Head Welder", label: "গ্রিল মিস্ত্রি হেড (Head Welder)" },
    { value: "Welder's Helper", label: "গ্রিল মিস্ত্রি সহকারী (Welder's Helper)" },
    { value: "Lift + Generator / Substation", label: "লিফট + জেনারেটর / সাবস্টেশন (Lift + Generator / Substation)" }
  ];
  