// src/constants/constants.js

export const BILL_DESCRIPTIONS = [
  { value: "Am Kat", label: "1. আম গাছ কাটা (Am Kat)" },
  { value: "Architect", label: "2. আর্কিটেক্ট (Architect)" },
  { value: "Bricks Purchase", label: "3. ইট ক্রয় (Bricks Purchase)" },
  { value: "Broker", label: "4. ব্রোকার (Broker)" },
  { value: "Cement", label: "5. সিমেন্ট (Cement)" },
  { value: "Chipping Head", label: "6. চিপিং মিস্ত্রি হেড (Chipping Head)" },
  { value: "Chipping Helper", label: "7. চিপিং মিস্ত্রি সহকারী (Chipping Helper)" },
  { value: "Concrete-Casting", label: "8. ঢালাই (Concrete Casting)" },
  { value: "Day Labour Bill", label: "9. দিনমজুর বিল (Day Labour Bill)" },
  { value: "Deed", label: "10. দলিল (Deed)" },
  { value: "Door Frame Purchase", label: "11. চৌকাঠ ক্রয় (Door Frame Purchase)" },
  { value: "Door Purchase", label: "12. দরজা ক্রয় (Door Purchase)" },
  { value: "Electric Items Purchase", label: "13. বৈদ্যুতিক সরঞ্জাম কেনা (Electric Items Purchase)" },
  { value: "Electrician", label: "14. ইলেকট্রিশিয়ান (Electrician)" },
  { value: "Engineer Salary", label: "15. ইঞ্জিনিয়ার বেতন (Engineer Salary)" },
  { value: "Guard Salary", label: "16. গার্ডের বেতন (Guard Salary)" },
  { value: "Hardware Materials", label: "17. হার্ডওয়্যার মালামাল (Hardware Materials)" },
  { value: "Head Painter", label: "18. রং মিস্ত্রি হেড (Head Painter)" },
  { value: "Head Welder", label: "19. গ্রিল মিস্ত্রি হেড (Head Welder)" },
  { value: "Lift + Generator / Substation", label: "20. লিফট + জেনারেটর / সাবস্টেশন (Lift + Generator / Substation)" },
  { value: "Maid Salary", label: "21. বুয়া বেতন (Maid Salary)" },
  { value: "Marketing Expenses", label: "22. মার্কেটিং খরচ (Marketing Expenses)" },
  { value: "Mati Kata", label: "23. মাটি কাটা (Mati Kata)" },
  { value: "Miscellaneous", label: "24. বিবিধ (Miscellaneous)" },
  { value: "Mobile Bill", label: "25. মোবাইল বিল (Mobile Bill)" },
  { value: "Office Cost", label: "26. অফিস খরচ (Office Cost)" },
  { value: "Office Deposit", label: "27. অফিস ডিপোজিট (Office Deposit)" },
  { value: "Overtime Bill", label: "28. ওভারটাইম বিল (Overtime Bill)" },
  { value: "Paint Purchase", label: "29. রং ক্রয় (Paint Purchase)" },
  { value: "Painter's Helper", label: "30. রং মিস্ত্রি সহকারী (Painter's Helper)" },
  { value: "Piling Expense", label: "31. পাইলিং খরচ (Piling Expense)" },
  { value: "Plan Pass/Approval", label: "32. প্ল্যান পাশ/অনুমোদন (Plan Pass/Approval)" },
  { value: "Project Deposit", label: "33. জমা (Project Deposit)" },
  { value: "Purchased Bamboo", label: "34. বাঁশ কেনা (Purchased Bamboo)" },
  { value: "RAJUK clearance", label: "35. রাজুক ক্লিয়ারেন্স (RAJUK clearance)" },
  { value: "Raj Mistri Head", label: "36. রাজ মিস্ত্রি হেড (Raj Mistri Head)" },
  { value: "Raj Mistri Helper", label: "37. রাজ মিস্ত্রি সহকারী (Raj Mistri Helper)" },
  { value: "Razia Tower Cost", label: "38. রাজিয়া টাওয়ার খরচ (Razia Tower Cost)" },
  { value: "Rod Mistri Head", label: "39. রড মিস্ত্রি হেড(Rod Mistri Head)" },
  { value: "Rod Mistri Helper", label: "40. রড মিস্ত্রি সহকারী (Rod Mistri Helper)" },
  { value: "Sanitary Goods", label: "41. স্যানিটারি মালামাল (Sanitary Goods)" },
  { value: "Sanitary Mistri Head", label: "42. স্যানিটারি মিস্ত্রি হেড (Sanitary Mistri Head)" },
  { value: "Sanitary Mistri Helper", label: "43. স্যানিটারি মিস্ত্রি সহকারী (Sanitary Mistri Helper)" },
  { value: "Sand", label: "44. বালি (Sand)" },
  { value: "Sign Board", label: "45. সাইন বোর্ড (Sign Board)" },
  { value: "Signing Money", label: "46. সাইনিং মানি (Signing Money)" },
  { value: "Soil Test", label: "47. মাটির পরীক্ষা (Soil Test)" },
  { value: "Staff Salary", label: "48. স্টাফ বেতন (Staff Salary)" },
  { value: "Steel Rod Purchase", label: "49. রড কেনা (Steel Rod Purchase)" },
  { value: "Stone", label: "50. পাথর (Stone)" },
  { value: "Thai Glass Purchase", label: "51. থাই গ্লাস ক্রয় (Thai Glass Purchase)" },
  { value: "Tiles Assembler Head", label: "52. টাইলস মিস্ত্রি হেড(Tiles Assembler Head)" },
  { value: "Tiles Assembler Helper", label: "53. টাইলস মিস্ত্রি সহকারী (Tiles Assembler Helper)" },
  { value: "Tiles Purchase", label: "54. টাইলস ক্রয় (Tiles Purchase)" },
  { value: "Utility", label: "55. ইউটিলিটি (Utility)" },
  { value: "VAT & TAX", label: "56. ভ্যাট এন্ড ট্যাক্স (VAT & TAX)" },
  { value: "Welder's Helper", label: "57. গ্রিল মিস্ত্রি সহকারী (Welder's Helper)" },
  { value: "MD Sir Personal Cost", label: "58. এমডি স্যার ব্যক্তিগত খরচ (MD Sir Personal Cost)" },
  { value: "R.T Deposit", label: "59. আর টি ডিপোজিট (R.T Deposit)" },
];

export const INVENTORY_ITEMS = [
  { value: "Balcony grill", label: "1. বারান্দার গ্রিল (Balcony grill)" },
  { value: "Brick Chips", label: "2. ইটের চিপস (Brick Chips)" },
  { value: "Bricks", label: "3. ইট (Bricks)" },
  { value: "Cable", label: "4. কেবল (Cable)" },
  { value: "Catdoor", label: "5. ক্যাটডোর (Catdoor)" },
  { value: "Cement", label: "6. সিমেন্ট (Cement)" },
  { value: "Chwkath", label: "7. চৌকাঠ (Chwkath)" },
  { value: "Colouring materials", label: "8. রং করার উপকরণ (Colouring materials)" },
  { value: "Door", label: "9. দরজা (Door)" },
  { value: "Electrical fittings Materials", label: "10. বৈদ্যুতিক ফিটিংস উপকরণ (Electrical fittings Materials)" },
  { value: "Kitchen Materials", label: "11. রান্নাঘরের উপকরণ (Kitchen Materials)" },
  { value: "Local sand", label: "12. স্থানীয় বালি (Local sand)" },
  { value: "Lock & kobja", label: "13. তালা ও কবজা (Lock & kobja)" },
  { value: "Ms Bar", label: "14. এমএস বার (Ms Bar)" },
  { value: "Pipe fittings", label: "15. পাইপ ফিটিংস (Pipe fittings)" },
  { value: "Rod", label: "16. রড (Rod)" },
  { value: "Sanitary fittings Materials", label: "17. স্যানিটারি ফিটিংস উপকরণ (Sanitary fittings Materials)" },
  { value: "Stone", label: "18. পাথর (Stone)" },
  { value: "Switch & socket", label: "19. সুইচ ও সকেট (Switch & socket)" },
  { value: "Sylhet sand", label: "20. সিলেট বালি (Sylhet sand)" },
  { value: "Thai glass", label: "21. থাই গ্লাস (Thai glass)" },
  { value: "Tiles", label: "22. টাইলস (Tiles)" },
  { value: "Window grill", label: "23. জানালার গ্রিল (Window grill)" },
  { value: "Working Tools", label: "24. কাজের সরঞ্জাম (Working Tools)" },
];
